services:
  auth_gateway:
    build:
      context: ..
      dockerfile: auth_gateway/Dockerfile
    container_name: auth_gateway
    command: uvicorn auth_gateway.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MASTER_ENC_KEY=${MASTER_ENC_KEY}